import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Copy,Check,Menu,X,ChevronDown,Globe2,Play,ArrowRight} from 'lucide-react';
import './style.css';

const officialLinks=['https://numer.ai','https://numer.ai/fund','https://docs.numer.ai/tournament/learn','https://forum.numer.ai','https://discord.gg/numerai','https://github.com/numerai/example-scripts','https://numer.ai/leaderboard'];
const external={target:'_blank',rel:'noopener noreferrer'};

const dict={
 en:{nav:['TOURNAMENTS','HEDGE FUND','DOCS','FORUM','DISCORD','GITHUB','LEADERBOARD'],login:'LOGIN',signup:'SIGN UP',hero:'ARCHITECT AN AI SCIENTIST',sub:'Use frontier AI to predict the stock market.',gm:'Achieve Grandmaster status.',api:'GET API KEYS',data:'START WITH HEDGE FUND QUALITY DATA.',dataSub:'It is clean and regularized, designed to be usable right away. Obfuscated, so it can be given out for free.',download:'DOWNLOAD DATA',explain:'Each id corresponds to a stock at a specific time era. The features describe the quantitative attributes of the stock. The target represents an abstract measure of future performance.',ml:'APPLY MACHINE LEARNING TO PREDICT THE STOCK MARKET.',mlSub:'Build a model using the example Python scripts. Everything you need to get started in one package.',clone:'CLONE EXAMPLE SCRIPTS',submit:'SUBMIT MODELS TO PREDICT THE STOCK MARKET.',submitSub:'Build reputation to claim your place on the leaderboard. Stake on your model to earn (or burn) cryptocurrency.',paid:'PAID TO DATA SCIENTISTS',learn:'LEARN MORE',join:'JOIN THE NETWORK AND BUILD THE WORLD’S LAST HEDGE FUND.',backed:'Backed by Union Square Ventures and the co-founder of Renaissance Technologies.',updates:'Receive updates about Numerai',email:'Email',subscribe:'SUBSCRIBE',legal:'ZERO TOLERANCE FOR ILLEGAL ACTIVITY',legalText:'ILLEGAL USE IS STRICTLY AND ABSOLUTELY PROHIBITED. This website may be used only for lawful educational and technical purposes. No person may use its services, code, content, data, models, links, or infrastructure to commit, facilitate, plan, conceal, promote, or assist fraud, market manipulation, unauthorized access, money laundering, sanctions evasion, infringement, or any other unlawful act. Any unlawful conduct is undertaken solely by the individual involved, without this website’s authorization, participation, endorsement, or benefit, and is unrelated to this website. The responsible person bears sole responsibility for their conduct and all resulting consequences. We may immediately block access, preserve relevant records, and cooperate with competent authorities where required or permitted by law. Nothing in this notice excludes any responsibility that cannot lawfully be excluded.',agree:'IF YOU INTEND TO ENGAGE IN ANY ILLEGAL ACTIVITY, DO NOT ACCESS OR USE THIS WEBSITE.',privacy:'PRIVACY',terms:'TERMS',copy:'Copy',copied:'Copied'},
 es:{nav:['TORNEOS','FONDO DE COBERTURA','DOCUMENTACIÓN','FORO','DISCORD','GITHUB','CLASIFICACIÓN'],login:'INICIAR SESIÓN',signup:'REGISTRARSE',hero:'DISEÑA UN CIENTÍFICO DE IA',sub:'Usa IA de vanguardia para predecir el mercado bursátil.',gm:'Alcanza el estatus de Gran Maestro.',api:'OBTENER CLAVES API',data:'EMPIEZA CON DATOS DE CALIDAD INSTITUCIONAL.',dataSub:'Limpios, regularizados y listos para usar. Ofuscados para poder distribuirlos gratuitamente.',download:'DESCARGAR DATOS',explain:'Cada id corresponde a una acción en un momento específico o era. Las variables describen sus atributos cuantitativos y el objetivo representa una medida abstracta del rendimiento futuro.',ml:'APLICA APRENDIZAJE AUTOMÁTICO AL MERCADO.',mlSub:'Crea un modelo con los scripts de ejemplo en Python. Todo lo necesario para empezar en un solo paquete.',clone:'CLONAR SCRIPTS DE EJEMPLO',submit:'ENVÍA MODELOS PARA PREDECIR EL MERCADO.',submitSub:'Construye tu reputación y ocupa un lugar en la clasificación. Apuesta por tu modelo para ganar (o perder) criptomonedas.',paid:'PAGADO A CIENTÍFICOS DE DATOS',learn:'MÁS INFORMACIÓN',join:'ÚNETE A LA RED Y CONSTRUYE EL ÚLTIMO FONDO DEL MUNDO.',backed:'Respaldado por Union Square Ventures y el cofundador de Renaissance Technologies.',updates:'Recibe novedades sobre Numerai',email:'Correo electrónico',subscribe:'SUSCRIBIRME',legal:'TOLERANCIA CERO FRENTE A ACTIVIDADES ILEGALES',legalText:'EL USO ILEGAL ESTÁ ESTRICTA Y ABSOLUTAMENTE PROHIBIDO. Este sitio solo puede utilizarse con fines educativos y técnicos lícitos. Nadie puede utilizar sus servicios, código, contenido, datos, modelos, enlaces o infraestructura para cometer, facilitar, planificar, ocultar, promover o ayudar en fraudes, manipulación del mercado, acceso no autorizado, blanqueo de capitales, evasión de sanciones, infracciones u otros actos ilícitos. Cualquier conducta ilegal es realizada exclusivamente por la persona implicada, sin autorización, participación, aprobación ni beneficio de este sitio, y no guarda relación con él. La persona responsable asume íntegramente la responsabilidad por su conducta y sus consecuencias. Podemos bloquear inmediatamente el acceso, conservar los registros pertinentes y cooperar con las autoridades competentes cuando la ley lo exija o permita. Nada de este aviso excluye responsabilidades que legalmente no puedan excluirse.',agree:'SI PRETENDES REALIZAR ALGUNA ACTIVIDAD ILEGAL, NO ACCEDAS NI UTILICES ESTE SITIO.',privacy:'PRIVACIDAD',terms:'TÉRMINOS',copy:'Copiar',copied:'Copiado'}
};
const rows=[['n2b2e3dd163cb422','era1','0.75','…','0.00','0.25'],['n177021a571c94c8','era1','1.00','…','0.25','0.75'],['n7830fa4c0cd8466','era1','0.25','…','1.00','0.00'],['nc584a184cee941b','era1','0.25','…','0.00','1.00'],['nc5ab8667901946a','era1','0.75','…','0.25','0.25']];
const terminal={Codex:['# clone example-scripts, install MCP, and prompt Codex','git clone git@github.com:numerai/example-scripts.git','cd example-scripts && curl -sL https://numer.ai/install-codex-mcp.sh | bash','codex exec --yolo "find the best neural network architecture"'],Claude:['# install MCP and launch Claude Code','git clone git@github.com:numerai/example-scripts.git','cd example-scripts && ./install-claude-mcp.sh','claude "train a tournament model"'],Cursor:['# open the examples inside Cursor','git clone git@github.com:numerai/example-scripts.git','cursor example-scripts','Ask: build a robust ensemble model']};
function Terminal({t}){const [tab,setTab]=useState('Codex'),[copied,setCopied]=useState(false);const copy=()=>{navigator.clipboard?.writeText(terminal[tab].join('\n'));setCopied(true);setTimeout(()=>setCopied(false),1200)};return <div className="terminal"><div className="tabs"><i/><i/><i/>{Object.keys(terminal).map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}<button className="copy" onClick={copy}>{copied?<Check/>:<Copy/>}{copied?t.copied:t.copy}</button></div><pre>{terminal[tab].map((x,i)=><span key={x}><b>$</b> {x}{i<terminal[tab].length-1?'\n':''}</span>)}</pre></div>}
function App(){const [lang,setLang]=useState('en'),[menu,setMenu]=useState(false),t=dict[lang];return <main>
 <section className="hero mesh"><nav><a className="brand" href="https://numer.ai" {...external}><span className="mark">✣</span> NUMERAI</a><div className={'links '+(menu?'open':'')}>{t.nav.map((x,i)=><a href={officialLinks[i]} {...external} key={x}>{x}{i===0&&<ChevronDown/>}</a>)}</div><div className="actions"><button className="lang" onClick={()=>setLang(lang==='en'?'es':'en')}><Globe2/>{lang==='en'?'ES':'EN'}</button><a className="button ghost" href="https://numer.ai/login" {...external}>{t.login}</a><a className="button" href="https://numer.ai/signup" {...external}>{t.signup}</a><button className="hamb" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></nav>
 <div className="heroGrid"><div><h1>{t.hero}</h1><h2>{t.sub}</h2><h2>{t.gm}</h2><a className="button" href="https://numer.ai/signup" {...external}>{t.api}</a></div><Terminal t={t}/></div><hr/>
 <section className="data" id="s0"><h3>{t.data}</h3><p>{t.dataSub}</p><a className="button outline" href="https://numer.ai/data" {...external}>{t.download}</a><div className="table"><div className="tr head">{['id','era','feature0','…','featureX','target'].map((x,i)=><span key={i}>{x}</span>)}</div>{rows.map((r,ri)=><div className="tr" key={r[0]}>{r.map((x,i)=><span key={ri+'-'+i}>{x}</span>)}</div>)}</div><p className="caption">{t.explain}</p></section></section>
 <section className="light" id="s1"><div className="sectionHead"><h3>{t.ml}</h3><p>{t.mlSub}</p><button className="dark">{t.clone}</button></div><div className="codeBlock"><div className="code"><div className="codeTop"><i/><i/><i/><span>model.py</span></div><pre>{`import pandas as pd\nfrom xgboost import XGBRegressor\n\ntraining = pd.read_parquet("train.parquet")\nfeatures = training.filter(like="feature_")\ntarget = training["target"]\n\nmodel = XGBRegressor(max_depth=5, n_estimators=2000)\nmodel.fit(features, target)\npredictions = model.predict(features)`}</pre></div><div className="prediction"><span>STAKED MODELS</span><strong>4,982</strong><div className="bars">{[40,72,55,90,66,82,48,74,96,62,86,57].map((x,i)=><i key={i} style={{height:x+'%'}}/>)}</div></div></div></section>
 <section className="submit mesh" id="s2"><h3>{t.submit}</h3><p>{t.submitSub}</p><div className="stat"><span>{t.paid}</span><strong>$ 42,918,403</strong><small>NMR 11,437,289</small></div></section>
 <section className="learn light" id="s3"><h3>{t.learn}</h3><div className="video"><iframe src="https://www.youtube-nocookie.com/embed/dhJnt0N497c" title="Numerai — The Hardest Data Science Tournament" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen/></div><div className="moreVideos"><iframe src="https://player.vimeo.com/video/205032211" title="Introducing Numeraire" allow="autoplay; fullscreen; picture-in-picture" allowFullScreen/><iframe src="https://www.youtube-nocookie.com/embed/GWeC2PK4yXQ" title="Numerai Signals" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/></div></section>
 <footer><div className="join"><h3>{t.join}</h3><p>{t.backed}</p></div><div className="footerGrid"><div><a className="brand" href="https://numer.ai" {...external}><span className="mark">✣</span> NUMERAI</a><h4>{t.updates}</h4><div className="email"><input placeholder={t.email}/><button>{t.subscribe}<ArrowRight/></button></div><div className="socials"><a href="https://blog.numer.ai" {...external}>BLOG</a><a href="https://x.com/numerai" {...external}>X / TWITTER</a><a href="https://discord.gg/numerai" {...external}>DISCORD</a><a href="https://github.com/numerai" {...external}>GITHUB</a></div></div><div className="legal"><h4>{t.legal}</h4><p>{t.legalText}</p><strong>{t.agree}</strong></div></div><div className="bottom"><span>© 2026 NUMERAI INSPIRED DEMO · INDEPENDENT UI RECREATION</span><div><a href="https://numer.ai/privacy" {...external}>{t.privacy}</a><a href="https://numer.ai/terms" {...external}>{t.terms}</a><button className="lang" onClick={()=>setLang(lang==='en'?'es':'en')}><Globe2/>{lang==='en'?'ESPAÑOL':'ENGLISH'}</button></div></div></footer>
 </main>}
createRoot(document.getElementById('root')).render(<App/>);
